@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package design.aeonic.catbottles.registry;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;