@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package design.aeonic.catbottles.recipe.virtual;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;