@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package design.aeonic.catbottles.content.bottles;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;